version: '2'
services:
  webpack:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webpack
    command: npm start
    ports:
      - "8080:8080"
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=dev
